INSERT OR IGNORE INTO pages (slug, title, content_md, image_url, updated_at) VALUES 
('contact', 'Contact Us', 'We would love to hear from you. For support with any of our project combos, please include your Order ID and Razorpay Payment ID.\n\n### General Inquiries\nEmail: technicaltriveniyt@gmail.com\n\n### Business & Sponsorships\nFor YouTube sponsorships, part reviews, or affiliate partnerships, please email the address above with "Sponsorship" in the subject line.\n\nWe usually reply within 24-48 business hours.', '', 1700000000),

('how-it-works', 'How It Works', '### 1. Browse Projects\nExplore our catalog of electronics and robotics projects. Each project page provides a free overview, parts list, and step-by-step instructions.\n\n### 2. Get the Combo\nFor an accelerated build, purchase the **Project Combo Pack**. This instantly unlocks all premium deliverables:\n- Full Source Code (`.ino`, `.cpp`, `.py`, etc.)\n- High-resolution Schematics & Wiring Diagrams\n- 3D Print Files (`.stl`)\n- Private Video guides or additional documentation\n\n### 3. Build & Learn\nOnce purchased, you will receive an email with your secure download link. You can also re-download your files anytime from the My Purchases page using your email address.', '', 1700000000),

('terms', 'Terms & Conditions', 'Last updated: October 2026\n\nWelcome to Technical Triveni. By purchasing our digital products (Project Combos, Source Code, 3D Models), you agree to the following terms:\n\n### 1. Digital Products\nAll products sold are digital downloads. No physical components, boards, or materials are shipped. You are purchasing intellectual property (code, diagrams, models) for educational purposes.\n\n### 2. License & Usage\nYou may use the provided code and designs for your personal, educational, or university projects. You may NOT resell, redistribute, or publish the source files or premium diagrams online.\n\n### 3. Liability\nElectronics and robotics involve inherent risks, including but not limited to electrical shock, fire, or component damage. Technical Triveni provides these guides for educational purposes and assumes no liability for injury, damage, or loss of equipment resulting from following our tutorials.', '', 1700000000),

('privacy', 'Privacy Policy', 'Last updated: October 2026\n\nTechnical Triveni ("we", "our") respects your privacy. \n\n### Data We Collect\n- **Order Information:** Name, Email address, and transaction IDs (handled securely via Razorpay). We do NOT store or process your credit card or UPI details on our servers.\n- **Communication:** Messages sent via our contact form.\n\n### How We Use Your Data\nWe use your email exclusively to deliver your digital purchases, provide technical support, and send critical updates regarding a project you purchased.\n\n### Third-Party Services\nWe use Razorpay for payment processing and Cloudflare for site security and performance. These providers have their own privacy policies governing data processing.', '', 1700000000),

('disclaimer', 'Safety Disclaimer', '### Educational Purposes Only\nThe content, tutorials, schematics, and source code provided by Technical Triveni are strictly for educational and hobbyist purposes.\n\n### High Voltage & Batteries\nProjects involving mains voltage (110V/220V) or Lithium-Polymer (LiPo) batteries present serious risks of fire, shock, or injury. If you are a beginner, seek supervision from a qualified instructor or engineer before attempting these builds.\n\nTechnical Triveni is not responsible for any damage, injury, or loss of life resulting from the reproduction of our projects.', '', 1700000000),

('affiliate', 'Affiliate Disclosure', 'Technical Triveni participates in various affiliate marketing programs. \n\nWhen you click on component links (e.g., to Amazon India, Robu.in, or MakerBazaar) in our Parts Lists and make a purchase, we may earn a small commission at **no additional cost to you**.\n\nThis helps support the channel and allows us to keep publishing free tutorials and open-source project guides. We only recommend components and stores that we have personally tested and trust.', '', 1700000000),

('cookies', 'Cookie Policy', 'We use essential cookies to ensure the website functions correctly:\n\n- **Session Cookies:** Used to securely authenticate admin users.\n- **Security Cookies:** Managed by Cloudflare (Turnstile) to protect our checkout and contact forms from bots and spam.\n- **Analytics:** We use privacy-friendly, cookieless analytics to understand site traffic.\n\nWe do not use tracking cookies for third-party advertising.', '', 1700000000),

('refund', 'Refund & Cancellation Policy', '### Digital Goods\nDue to the nature of digital goods (source code, schematics, 3D files), **all sales are final and non-refundable once the files have been downloaded**.\n\n### Exceptions\nIf you accidentally purchase the same project twice, or if the ZIP file is demonstrably corrupt and we cannot provide a working replacement, please contact us within 7 days at technicaltriveniyt@gmail.com with your Order ID for a refund.\n\n### Delivery\nDigital files are delivered instantly via email upon successful payment via Razorpay. If you do not receive the email, please check your spam folder or contact support.', '', 1700000000);
