import { defineMiddleware } from 'astro:middleware';
import { env } from 'cloudflare:workers';
import { getSession, ensureCsrfToken } from './lib/auth';

/**
 * Runs on every request. Responsibilities:
 *   1. Resolve the admin session + CSRF token into `locals`.
 *   2. Guard /admin and /api/admin routes.
 *   3. Attach security headers (the CSP itself is generated by Astro — see
 *      `security.csp` in astro.config.mjs).
 */
export const onRequest = defineMiddleware(async (context, next) => {
  const { locals, cookies, url } = context;

  // --- session + csrf ---
  locals.admin = await getSession(env, cookies);
  locals.csrfToken = ensureCsrfToken(cookies);

  // --- route guards ---
  const path = url.pathname;
  const isAdminPage = path === '/admin' || path.startsWith('/admin/');
  const isAdminApi = path.startsWith('/api/admin/');
  const isLogin = path === '/admin/login' || path === '/api/admin/login';

  if ((isAdminPage || isAdminApi) && !isLogin && !locals.admin) {
    if (isAdminApi) {
      return new Response(JSON.stringify({ error: 'Unauthorized' }), {
        status: 401,
        headers: { 'content-type': 'application/json' },
      });
    }
    const nextPath = encodeURIComponent(path + url.search);
    return context.redirect(`/admin/login?next=${nextPath}`);
  }

  const response = await next();

  // --- security headers (CSP is handled by Astro's security.csp) ---
  applySecurityHeaders(response, url.protocol === 'https:');
  return response;
});

function applySecurityHeaders(res: Response, isHttps: boolean) {
  const h = res.headers;

  h.set('X-Content-Type-Options', 'nosniff');
  h.set('Referrer-Policy', 'strict-origin-when-cross-origin');
  h.set('X-Frame-Options', 'DENY');
  h.set('Permissions-Policy', 'camera=(), microphone=(), geolocation=(), interest-cohort=()');
  h.set('Cross-Origin-Opener-Policy', 'same-origin');
  if (isHttps) {
    h.set('Strict-Transport-Security', 'max-age=31536000; includeSubDomains; preload');
  }
}
